name: dating_app
description: A Flutter dating app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+3

environment:
  #sdk: ">=2.1.0 <3.0.0"
  sdk: ">=2.3.0-dev.0.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttery:
    git:
      url: git://github.com/mtellect/fluttery
  flutter_swiper: ^1.1.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_sparkline: "^0.1.0"
  flutter_staggered_grid_view: "^0.2.1"
  sqflite: ^1.1.5

  intl: ^0.15.7
  http: ^0.12.0+1
  flutter_circular_chart: ^0.1.0
  charts_flutter: ^0.6.0
  meta: ^1.0.5
  shimmer: ^1.0.0
  animated_text_kit: ^1.3.1
  url_launcher: ^5.1.2
  bubble_tab_indicator: ^0.1.3
  cached_network_image: ^2.0.0
  page_indicator: ^0.1.0
  page_view_indicator: ^0.3.0+1
  font_awesome_flutter: ^8.2.0
  swipedetector: ^1.2.0
  #chopper: ^2.4.2
  provider: ^3.0.0+1
  connectivity: ^0.4.9+2
  build_runner: ^1.7.4
  built_value_generator: ^7.0.9
  built_value: ^7.0.9
  flutter_bloc: ^1.0.0
  equatable: ^0.6.1
  flutter_widgets: ^0.1.9
  datetime_picker_formfield: ^1.0.0
  circular_profile_avatar: ^1.0.6
  multi_image_picker: ^4.6.1

  #chopper_generator: ^2.4.2
  chopper_generator: 3.0.4
  chopper: 3.0.3
  progress_dialog: ^1.2.0
  flutter_icons: ^1.0.0+1
  outline_material_icons: ^0.1.1
  permission_handler: ^4.2.0+hotfix.3
  #file_picker: ^1.4.3+2
  file_picker: 2.1.7
  after_layout: ^1.0.7+2
  json_serializable: ^3.2.2
  lite_rolling_switch: ^0.1.1
  shared_preferences: ^0.5.6+1
  flutter_svg: ^0.15.0
  diacritic: ^0.1.0
  #keyboard_visibility: ^0.5.6
  flutter_range_slider: "^1.4.0"
  firebase_auth: ^0.15.4
  #google_sign_in: ^4.1.1
  google_sign_in: ^4.5.4
  flutter_facebook_login: ^3.0.0
  #flutter_downloader: ^1.5.1
  flutter_downloader:
    git:
      url: https://github.com/fluttercommunity/flutter_downloader.git
      ref: embedding-v2
  moor_flutter: ^3.1.0
  moor_generator: ^3.1.0
  dio: ^3.0.10
  dotted_border: ^1.0.6
  data_connection_checker: ^0.3.4
  flutter_masked_text: ^0.8.0
  toast: ^0.1.5
  flutter_keyboard_visibility: ^2.0.0
  rect_getter: ^0.1.0
  pull_to_refresh: ^1.6.2
  carousel_slider: ^2.3.1
  scroll_to_index: ^1.0.6
  fluttertoast: ^7.1.8
  flutter_local_notifications: ^1.3.0
  #lipa_na_mpesa_online: 1.0.1
  flutter_dotenv: 3.1.0


flutter:

  uses-material-design: true


  assets:
    - assets/drawables/
    - assets/images/

    - assets/login_logo.png

    - assets/images/app_icon.png
    - assets/images/ava6.png

    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/img5.jpg
    - assets/images/img0.jpg
    - assets/images/hookup.png
    - assets/images/swipe.png
    - assets/images/match.png
    - assets/images/avatar.jpg
    - assets/images/chat2.png
    - assets/images/ic_chat.png
    - assets/images/hookup_icon.png
    - assets/images/hookup_icon_small.png
    - assets/images/lightening.png
    - assets/illustrations/profile_pic.png
    - assets/illustrations/profile_pic_trans.png
    - assets/onb/onboarding0.png

    - assets/flags/
    - assets/svg/
    - assets/png/
    - assets/png/shopping_cart.png
    - assets/onb/
    - assets/logos/
    - assets/illustrations/
    - .env


  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family: Canterbury
      fonts:
        - asset: assets/fonts/Animated/Canterbury.ttf

    - family: HelloStockholm
      fonts:
        - asset: assets/fonts/Animated/HelloStockholm.otf

    - family: Horizon
      fonts:
        - asset: assets/fonts/Animated/Horizon.otf

    - family: Bobbers
      fonts:
        - asset: assets/fonts/Animated/Bobbers.ttf

    - family: Agne
      fonts:
        - asset: assets/fonts/Animated/Agne.otf


    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          style: normal
        - asset: assets/fonts/Quicksand_Bold.otf
          weight: 700


    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway-Medium.ttf

    - family: Nirmala
      fonts:
        - asset: assets/fonts/Nirmala.ttf
    - family: ProximaNovaSoft
      fonts:
        - asset: assets/fonts/ProximaNovaSoft-Regular.otf
          style: normal
        - asset: assets/fonts/ProximaNovaSoft-Semibold.otf
          style: normal
        - asset: assets/fonts/ProximaNovaSoft-Bold.otf
          weight: 700

    - family: MarkerCustomIcon
      fonts:
        - asset: assets/fonts/CustomIcons/MarkerCustomIcon.ttf

    - family: GothamRounded-Book
      fonts:
        - asset: assets/fonts/GothamRounded/gothamrounded-book.otf

    - family: GothamRounded-Light
      fonts:
        - asset: assets/fonts/GothamRounded/gothamrounded-light.otf

    - family: GothamRoundedMedium_21022
      fonts:
        - asset: assets/fonts/GothamRounded/gothamroundedmedium_21022.ttf

    - family: GothamRoundedBook_21018
      fonts:
        - asset: assets/fonts/GothamRounded/gothamroundedbook_21018.ttf

    - family: GothamRounded-Medium
      fonts:
        - asset: assets/fonts/GothamRounded/gothamrounded-medium.otf

    - family: AvenirLTStd-Black
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-Black.otf

    - family: AvenirLTStd-BlackOblique
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-BlackOblique.otf

    - family: AvenirLTStd-Book
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-Book.otf

    - family: AvenirLTStd-BookOblique
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-BookOblique.otf

    - family: AvenirLTStd-Heavy
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-Heavy.otf

    - family: AvenirLTStd-HeavyOblique
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-HeavyOblique.otf

    - family: AvenirLTStd-Light
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-Light.otf

    - family: AvenirLTStd-LightOblique
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-LightOblique.otf

    - family: AvenirLTStd-Medium
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-Medium.otf

    - family: AvenirLTStd-MediumOblique
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-MediumOblique.otf

    - family: AvenirLTStd-Oblique
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-Oblique.otf

    - family: AvenirLTStd-Roman
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-Roman.otf